# Generated by Django 2.0.3 on 2018-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180330_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='controller',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Controller',
        ),
    ]
