# Generated by Django 2.0.3 on 2018-03-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180330_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='F', max_length=1),
            preserve_default=False,
        ),
    ]
