# Generated by Django 2.0.3 on 2018-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180331_0741'),
        ('devices', '0006_auto_20180331_0747'),
    ]

    operations = [
    ]
