# Generated by Django 2.0.3 on 2018-03-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180331_0741'),
        ('devices', '0007_auto_20180331_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarydevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='fuzzydevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.DeleteModel(
            name='BinaryDevice',
        ),
        migrations.DeleteModel(
            name='FuzzyDevice',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
