# Generated by Django 2.0.3 on 2018-03-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20180331_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Device')),
                ('state', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('next_state', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='FuzzyDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.Device')),
                ('state', models.IntegerField(choices=[(0, 'Off'), (1, 'Low'), (2, 'High')], default=0)),
                ('next_state', models.IntegerField(choices=[(0, 'Off'), (1, 'Low'), (2, 'High')], default=0)),
            ],
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='B', max_length=1),
            preserve_default=False,
        ),
    ]
