# Generated by Django 2.0.3 on 2018-03-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20180331_0809'),
        ('devices', '0009_auto_20180331_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarydevice',
            name='device_ptr',
        ),
        migrations.RemoveField(
            model_name='fuzzydevice',
            name='device_ptr',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='BinaryDevice',
        ),
        migrations.DeleteModel(
            name='FuzzyDevice',
        ),
    ]
