# Generated by Django 2.0.3 on 2018-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20180331_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mean_usage',
            field=models.FloatField(default=1.0),
        ),
    ]
