# Generated by Django 2.0.3 on 2018-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_mean_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='next_state',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
    ]
