# Generated by Django 2.0.3 on 2018-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeddata',
            name='state',
            field=models.CharField(default='off', max_length=16),
        ),
        migrations.AlterField(
            model_name='loggeddata',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
