# Generated by Django 2.0.3 on 2018-03-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180330_1155'),
        ('analytics', '0002_auto_20180330_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedRoomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('value', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Room')),
            ],
        ),
        migrations.RenameModel(
            old_name='LoggedData',
            new_name='LoggedDeviceData',
        ),
    ]
