# Generated by Django 2.0.3 on 2018-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20180331_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedroomdata',
            name='room',
        ),
        migrations.AddField(
            model_name='loggedroomdata',
            name='hum_value',
            field=models.FloatField(default=0),
        ),
    ]
